id: ICE583F6A
legacy_id: P000510
ocr_import_info:
  bdrc_scan_id: W4CZ74475
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T16:28:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:09:06.741995+00:00'
last_modified: 2022-09-04 05:09:23.977655
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74475
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74475
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐུ་འབུམ་གདན་རབས།
  author: གསེར་ཏོག་བློ་བཟང་ཚུལ་ཁྲིམས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5066943799733433
  ocr_word_median_confidence_index: 0.4699999988079071
quality: null
bases:
  I4CZ74477:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74477
      total_pages: 620
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74477.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.5066943799733433
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
